language: objective-c
osx_image: xcode10

script:
  - xcodebuild -project Einsteinium.xcodeproj -scheme Einsteinium -configuration Debug -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 8' clean build
